project:
  type: website
  output-dir: docs

website:
  title: "GIS_capsule_course"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Day1.qmd
      - Day2.qmd
      - Day3.qmd
      - Day4.qmd
      - Data

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

