project:
  type: website
  output-dir: docs

website:
  title: "GIS@GSSI"
  twitter-card: true
  open-graph: true
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/rsfrankl/GIS_capsule_course
      - icon: twitter
        href: https://x.com/rsfrankl
      - icon: linkedin
        href: https://www.linkedin.com/in/rachelsfranklin/
      - icon: envelope-fill
        href: mailto:rachel.franklin@newcastle.ac.uk
  sidebar:
    style: "floating"
    search: true
    border: true
    contents:
      - section: "Monday"
        contents:
          - Pages/Introduction_page.qmd
          - Pages/Getting_started_QGIS.qmd
          - Pages/GIS_commandments.qmd
      - section: "Tuesday"
        contents:
          - Pages/GIS_basics.qmd
          - Pages/Tutorial1.qmd
      - section: "Wednesday"
        contents: 
          - Pages/Cartography_101.qmd
          - Pages/Tutorial2.qmd
          - Pages/Tutorial2_part2.qmd
          - Pages/Intro_spatial_analysis.qmd
          - Pages/Tutorial3.qmd
      - section: "Thursday"
        contents:
          - Pages/More_spatial_analysis.qmd
          - Pages/Tutorial4.qmd
      - section: "Friday"
        contents:
          - Pages/Progettino.qmd
      - section: "Data"
        contents:
          - Pages/Data.qmd
          - Pages/Finding_spatial_data.qmd
  page-footer:
    left: "Rachel Franklin, copyright 2024"
    right: "Built with brute force {{< fa dumbbell >}} and [Quarto](https://quarto.org)"

format:
  html:
    theme: [Default, Styles/website_styles.scss]
    mainfont: Quicksand
    toc: true
    page-layout: full

editor: visual

