project:
  type: website
  output-dir: docs

website:
  title: "GIS@GSSI"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "floating"
    search: true
    border: true
    contents:
      - section: "Monday"
        contents:
          - Pages/Introduction_page.qmd
          - Pages/Getting_started_QGIS.qmd
          - Pages/GIS_commandments.qmd
      - section: "Tuesday"
        contents:
          - Pages/GIS_basics.qmd
          - Pages/Tutorial1.qmd
      - section: "Wednesday"
        contents: 
          - Pages/Cartography_101.qmd
          - Pages/Tutorial2.qmd
          - Pages/Tutorial2_part2.qmd
          - Pages/Intro_spatial_analysis.qmd
          - Pages/Tutorial3.qmd
      - section: "Thursday"
        contents:
          - Thursday.qmd
      - section: "Friday"
        contents:
          - Friday.qmd
      - section: "Data"
        contents:
          - Pages/Data.qmd
          - Pages/Finding_spatial_data.qmd
  page-footer:
    left: "Rachel Franklin, copyright 2024"
    right: "Built with brute force {{< fa dumbbell >}} and [Quarto](https://quarto.org)"

format:
  html:
    theme: [Default, Styles/website_styles.scss]
    mainfont: Quicksand
    toc: true
    page-layout: full

editor: visual

