---
title: "About"
css: /Styles/website_styles.scss
---

## About QGIS\@GSSI

These materials support the summer course in spatial data, visualization, and GIS in the [Regional Science and Economic Geography](https://www.gssi.it/education/regional-science-economic-geography) program at the [Gran Sasso Science Institute](https://www.gssi.it) (GSSI) in L'Aquila, Italy.

## About your course lead: Rachel Franklin

I'm a quantitative human geographer and executive director of the [Center for Geographic Analysis (CGA)](https://gis.harvard.edu) at Harvard University. Before that, I was Professor of Geographical Analysis in the Centre for Urban and Regional Development Studies (CURDS) at Newcastle University and also the group lead for liveability in the Science of Cities and Regions Programme at [The Alan Turing Institute](https://www.turing.ac.uk), the UK's national institute for data science and AI.

I've taught spatial analysis GIS to a range of audiences for over 15 years, including several times at the GSSI, and have taught quantitative and demographic methods for over 20 years.

You can find out more about me [here](https://www.rachelfranklin.org).

## About these teaching materials

These materials are aimed at students who are experts in something *other* than geography and spatial analysis. The primary goal is twofold: to illustrate the potential and utility of spatial thinking and methods and to provide a user-friendly introduction to applying spatial thinking and methods.

The code and license for all these materials can be found on GitHub [{{< fa brands github >}}](https://github.com/rsfrankl/GIS_capsule_course).
