---
title: "Course Data"
css: /Styles/website_styles.scss
---

For your *progettino*, you'll locate and use your own data. See [Finding spatial data](Finding_spatial_data.qmd) for some ideas.

## Practical Data

For practicals, we'll use the data below. To work with these datasets in QGIS, you'll need to download the zipped folder and then expand and save in your preferred location (I suggest a new folder on your Desktop or in your Documents). **Pay attention to where you save your data and your QGIS projects! And ideally you keep it all together in one folder!**

Once unzipped, most data are in geopackage (gpkg) format---a container holding several spatial layers.

-   [Rome Data](Rome_Data.zip)
-   [European Union (EU) Example](EU_Mapping_Example.zip)
-   [Spatial Analysis Data](Spatial_Analysis.zip)

### Where do these datasets come from?

Short answer: a variety of places.

-   From the [Rome Geoportal](https://www.comune.roma.it/TERRITORIO/nic-gwt/#):
    -   Popolazione Residente Istat 2011 (Population Resident ISTAT 2023)
    -   Luoghi della Cultura (Cultural Locations)
    -   Zone Urbanistiche (Urban Zones)
    -   Waterways (Idrografia)
-   From [Inside Airbnb](http://insideairbnb.com/get-the-data):
    -   AirBnb listings from March 2023
    -   Rome Neighborhoods
-   From Eurostat:
    -   [NUTS2 Regions (2016 version)](https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics)
    -   [2020 Total Fertility Rates (table TGS00100)](https://ec.europa.eu/eurostat/data/database)
-   From [Roma Servizi per la Mobilità](https://romamobilita.it/it/tecnologie/dataset-geografici)
    -   Roman metro stations

**Note:** Many of these datasets have been cleaned and curated to make them easier to work with for practicals!
