---
title: "Progettino"
css: /Styles/website_styles.scss
---

## Independent work---expectations

It's a packed week, with lots to learn and practice. The purpose of the *progettino* is to provide space to apply concepts and methods independently, without the support of tutorials.

You don't have much time for this mini-project, so what is expected?

-   Decide on a topic or question that's interesting to you.
-   Locate relevant data.
-   Frame your question or topic spatially---for example, how do density, distance, proximity, or context matter?
-   Think about what sorts of methods and approaches might be useful?
-   You don't have much time, so no need to be over-ambitious! Focus on the achievable and interesting (to you).
-   I'm available to talk through ideas!

## Sharing with peers

On Friday morning we'll come together as a group to share what we've been working on.

-   About 5 minutes per person.
-   No need for a formal presentation---a map or two is sufficient!
-   This should be a positive process, a chance to reflect on how much you've learned, and an opportunity to learn more about your peers' interests and expertise!
